AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Posts Serverless Application


Resources:
  ImagePostsHandler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-image-posts-handler'
      Description: Image Posts Serverless Application Handler
      CodeUri: ./src/ImagePosts.Api/
      Handler: ImagePosts.Api
      Runtime: dotnet8
      MemorySize: 2048
      Tracing: Active
      Timeout: 600
      Environment:
        Variables:
          POSTS_TABLE: !Ref PostsTable
          COMMENTS_TABLE: !Ref CommentsTable
          IMAGE_BUCKET: !Ref ImageStorageBucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PostsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CommentsTable
        - S3CrudPolicy:
            BucketName: !Ref ImageStorageBucket
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '2.0'
            Path: /{proxy+}
            Method: ANY
        RootResource:
          PayloadFormatVersion: '2.0'
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY

  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: posts
      KeySchema:
        - AttributeName: PostId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: PostId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  
  CommentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: comments
      KeySchema:
        - AttributeName: CommentId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: CommentId
          AttributeType: S
        - AttributeName: PostId
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: PostIdIndex
          KeySchema:
            - AttributeName: PostId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  
  ImageStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  
  PublicS3ReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageStorageBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref ImageStorageBucket
                - /* 
              