name: infrastructureAsCodeValidation

on:
  push:
    branches:
      - main

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          
      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: SAM Build
        run: |
          sam build

      - name: Sam Validate
        run: |
          sam validate
